// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPhrLLXVIeGJ5il3Ygk5DAANA-QMoZqjE',
    appId: '1:254174956352:web:b3a084a8b29e6f293148a5',
    messagingSenderId: '254174956352',
    projectId: 'partners-in-faith',
    authDomain: 'partners-in-faith.firebaseapp.com',
    storageBucket: 'partners-in-faith.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXS16IrBOfDqlV8CzlO_POkZMccgjVbJk',
    appId: '1:254174956352:android:a7c6d87c5e0c6d0a3148a5',
    messagingSenderId: '254174956352',
    projectId: 'partners-in-faith',
    storageBucket: 'partners-in-faith.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMat6LQekNEZmN8ebxh71iTyo7scHCJg8',
    appId: '1:254174956352:ios:1fb0755eb1755f803148a5',
    messagingSenderId: '254174956352',
    projectId: 'partners-in-faith',
    storageBucket: 'partners-in-faith.appspot.com',
    iosClientId: '254174956352-p8nmpp796jj65d7b1lb07rc9938bff4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMat6LQekNEZmN8ebxh71iTyo7scHCJg8',
    appId: '1:254174956352:ios:f0f5ba27f826f4a33148a5',
    messagingSenderId: '254174956352',
    projectId: 'partners-in-faith',
    storageBucket: 'partners-in-faith.appspot.com',
    iosClientId: '254174956352-r15gdcoe3u4tocn591medko1fo2t8atf.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
